module.exports = {
    BOOK_CODE: 'BOOK',
    ARTICLE_BOOK_CODE: 'ARTICLE_BOOK',
    ARTICLE_MAGAZINE_CODE: 'ARTICLE_MAGAZINE',
    ARTICLE_NEWSPAPER_CODE: 'ARTICLE_NEWSPAPER',
    CONFERENCE_CODE: 'CONFERENCE',
    SITE_CODE: 'SITE',
};
