module.exports = {
    BOOK_CODE: 'BOOK_CODE',
    ARTICLE_BOOK_CODE: 'ARTICLE_BOOK_CODE',
    ARTICLE_MAGAZINE_CODE: 'ARTICLE_MAGAZINE_CODE',
    ARTICLE_NEWSPAPER_CODE: 'ARTICLE_NEWSPAPER_CODE',
    CONFERENCE_CODE: 'CONFERENCE_CODE',
    SITE_CODE: 'SITE_CODE',
};
